language: scala

scala:
  - 2.12.0
  - 2.11.8

env:
  - JDK=oraclejdk8
  - JDK=openjdk7
  - JDK=oraclejdk7

before_script:
  - jdk_switcher use $JDK

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.0
      env: JDK=oraclejdk7
    - scala: 2.12.0
      env: JDK=openjdk7
